# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1baa356faa672b008f76492d4b367e7c5145f1c917825ef9769724c35ae332db7c09c55e15975c4e8c8493bf9323f33cbccdc270ae0db7c856f8878ca934bf53

test:
  secret_key_base: 6216e690a032f9d9e4d5caf69368d3c92003c834615fe3ec899accbb8a99a6f10e14a6d76dbaad2b62172b295193457bdc89c5d40222f71365cbe066f6461776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
